import { useLanguage } from '../context/LanguageContext';
import { LocalLink as Link } from '../components/LocalLink';
export default function Instructions() {
  const { t } = useLanguage();
  return <article className="reading-page"><p className="eyebrow">{t("MANUAL DE LECTURA")}</p><h1 tabIndex={-1}>{t("Un pequeño ritual.")}<br /><em>{t("Diez descubrimientos.")}</em></h1><p className="lead">{t("The Tortured Poets Challenge es un juego de preguntas sobre Taylor Swift y William Shakespeare. Lee un fragmento en inglés e identifica su procedencia.")}</p>
    <div className="reading-grid"><section><h2>{t("01. Elige tu ritmo")}</h2><p><strong>{t("Sin prisa:")}</strong>{t(" todo el tiempo que necesites. ")}<strong>{t("A contrarreloj:")}</strong>{t(" veinte segundos por pregunta. El tiempo sigue pasando si cambias de pestaña y se detiene al responder.")}</p></section><section><h2>{t("02. Sigue tu intuición")}</h2><p>{t("Diez preguntas, una por obra, en orden aleatorio. Cada acierto suma 100 puntos. Una respuesta incorrecta o fuera de tiempo suma cero, sin restar puntos.")}</p></section><section><h2>{t("03. Pide una pista")}</h2><p>{t("Tienes tres por partida, como máximo una por pregunta. Si la utilizas, ese acierto vale 50 puntos. La pista no detiene el reloj.")}</p></section><section><h2>{t("04. Vuelve a leer")}</h2><p>{t("Descubre la obra, los créditos y el contexto después de cada respuesta. Al terminar puedes repasar solo los errores, sin reloj y con un marcador nuevo.")}</p></section></div>
    <section className="note"><h2>{t('Tres capítulos, un mismo archivo.')}</h2><p>{t('En Entre dos plumas identificas la procedencia; en La obra oculta eliges la canción o la obra entre cuatro títulos. Ambos comparten diez fragmentos, pistas y modos de tiempo.')}</p><p>{t('El hilo de las eras propone seis álbumes al azar. Arrastra las tarjetas desde ⠿ o usa los botones de subir y bajar para ordenar los lanzamientos originales. Puedes comprobar el orden tantas veces como necesites; al acertar, se revelan los años.')}</p><p>{t('El cuaderno guarda obras descubiertas, favoritos y hasta veinte partidas terminadas. Los sellos reflejan acciones reales y todo se borra al recargar. Puedes vaciarlo también desde su página.')}</p></section><aside className="note"><h2>{t("Lo que conviene saber")}</h2><p>{t("La interfaz está disponible en castellano e inglés británico. Los fragmentos conservan su inglés original. «Taylor Swift» identifica una canción de su repertorio: los créditos reconocen también a quienes la compusieron con ella.")}</p><p>{t("El catálogo inicial contiene diez fragmentos; las nuevas rondas cambian su orden. No necesitas cuenta. Al recargar o cerrar la página se pierde el progreso. Abandonar la partida borra el marcador.")}</p><p>{t("Puedes jugar con teclado: Tab para moverte, flechas para elegir modo y Enter o espacio para activar los botones.")}</p></aside><Link to="/" className="button">{t("Estoy lista para leer →")}</Link>
  </article>;
}
